services:
  - type: web
    name: option-spreads-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ANGEL_API_KEY
        sync: false
      - key: ANGEL_SECRET_KEY
        sync: false
      - key: ANGEL_CLIENT_CODE
        sync: false
      - key: ANGEL_PASSWORD
        sync: false
      - key: ANGEL_TOTP_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: https://option-spreads-analyzer.vercel.app,http://localhost:3000,http://localhost:5173
      - key: PORT
        value: "10000"
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /health