services:
  - type: web
    name: option-spreads-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ANGEL_API_KEY
        sync: false
      - key: ANGEL_SECRET_KEY
        sync: false
      - key: ANGEL_CLIENT_CODE
        sync: false
      - key: ANGEL_PASSWORD
        sync: false
      - key: ANGEL_TOTP_TOKEN
        sync: false
      - key: CORS_ORIGINS
<<<<<<< HEAD
        value: https://delta-deck-llp9-git-main-anirdths-projects.vercel.app/,http://localhost:5173,http://localhost:3000
=======
        value: https://delta-deck-llp9-git-main-anirdths-projects.vercel.app,http://localhost:5173,http://localhost:3000
>>>>>>> 96f231ee3be773c8e4a0ed8c1abfaffe5317b3c2
      - key: LOG_LEVEL
        value: INFO
      - key: PORT
        value: 10000
